### ISSUE TITLE
Automatic linking

### ISSUE THREAD

**Issue by metagn** [metagn/marggers#9]
Direct links can be ugly in pages, so it can help to not autolink, but it should still be an option. `uri.parseUri` does not fail on invalid chars, so will need a custom URI parser for this.

**Comment by hlaaftana** [comment]
Maybe allow supplying URL parser callback, if nil then use library URL parser, also allow custom start protocols on top of http: and https:

**Comment by metagn** [comment]
Not really feasible for performance IMO
